services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  pgdata:
    driver: local
